services:
  chatpie:
    container_name: chatpie-app
    image: chatpie:latest
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - '8300:8300'
    environment:
      - NO_HTTPS=1
    env_file:
      - .env
    dns:
      - 8.8.8.8 # Google's public DNS server
      - 8.8.4.4 # Google's public DNS server
    networks:
      - chatpie-networks
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: chatpie-db
    image: postgres:17
    env_file:
      - .env
    networks:
      - chatpie-networks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  chatpie-networks:
    driver: bridge
